# Generated by Django 5.0.6 on 2024-12-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='image.png', upload_to=''),
        ),
    ]
