# Generated by Django 5.1.3 on 2024-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_init_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='gifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('image', models.ImageField(blank=True, default='image.png', upload_to='')),
            ],
        ),
    ]
