# Generated by Django 5.1.3 on 2024-12-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_gifs_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gifs',
            new_name='gif',
        ),
    ]
