# Generated by Django 5.1.3 on 2024-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_detail_date_alter_detail_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, default='image.png', upload_to=''),
        ),
    ]
