# Generated by Django 5.1.3 on 2024-12-04 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_gifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifs',
            name='image',
            field=models.ImageField(blank=True, default='image.png', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
