# Generated by Django 5.1.3 on 2024-12-05 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_remove_detail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='body',
            field=models.TextField(),
        ),
    ]
