# Generated by Django 5.1.3 on 2024-12-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
